name: when_generator
description: A starting point for Dart libraries or applications.
version: 3.0.6
publish_to: 'none'

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  when:
    git:
      url: https://github.com/ravendm/spices.git
      path: packages/when/when
      ref: 3.0.6
  source_gen: ^1.2.6
  analyzer: ^5.13.0
  build: ^2.4.0

dev_dependencies:
  build_runner: ^2.2.0
