name: copy_with_generator
description: A new flutter plugin project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  copy_with:
    path: ./../copy_with
  #    git:
  #      url: https://github.com/urusai88/spices.git
  #      path: packages/copy_with/copy_with
  source_gen: ^1.2.0
  analyzer: ^4.6.0
  build: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.0
